// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhcscsczogemcbhkardz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoY3Njc2N6b2dlbWNiaGthcmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMjkyNzIsImV4cCI6MjA4NTkwNTI3Mn0.VipnLhYUyXspMNnhTJ6GlNNhf4EfrsCxhbWQLJDnLUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});